source: source
destination: site
markdown: rdiscount
pygments: true
permalink: /blog/:year/:month/:day/:title
url: http://dev.cpjobling.org.uk
multiviews: true
sass: false
haml: true
post_defaults:
  layout: blog_post